name: Unlock MI Account

on:
  # schedule:
    # - cron: '51 15 * * *'
  workflow_dispatch:

jobs:
  status:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.13.3'

      - name: Install Dependencies
        run: |
          pip install uv
          uv venv
          uv pip install -r ./requirements.txt

      - name: Run Unlock Script
        env:
          COOKIE_VALUE: ${{ secrets.COOKIE_VALUE }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOPIC_ID: ${{ secrets.TELEGRAM_TOPIC_ID }}
        run: |
          export TERM=xterm
          uv run python3 -u ./unlock_mi.py